### ISSUE TITLE
Demo error on Safari

### ISSUE THREAD

**Issue by lb-97** [JosuaKrause/searchspace#5]
<img width="1433" alt="Screen Shot 2023-07-27 at 4 43 06 PM" src="https://github.com/JosuaKrause/searchspace/assets/42465606/36b2be1c-544e-4755-875c-8993cff0bf17">

**Comment by JosuaKrause** [comment]
3d18b119b658254389c9ae6b8a7a8c86449dfffa should fix this issue. Let me know if it works now or if other errors show up.
